{{- if .Values.tokenExternalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "tokenExternalSecret.name is required" .Values.tokenExternalSecret.name }}
  namespace: {{ required "namespace.name is required" .Values.namespace.name }}
  labels:
    {{- include "carbon.labels" . | nindent 4 }}
  annotations:
    {{- include "carbon.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.tokenExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.tokenExternalSecret.source.kind }}
    name: {{ .Values.tokenExternalSecret.source.name }}
  target:
    name: {{ .Values.tokenExternalSecret.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.tokenExternalSecret.source.folder | quote }}
{{- end -}}
