{ treefmt-nix, pkgs, ... }:
let
  fmt = {
    projectRootFile = "flake.nix";

    # ### workspace-formatters
    # #### source: workspace
    programs = {
      actionlint.enable = true;
      nixfmt.enable = true;
      prettier = {
        enable = true;
        excludes = [
          ".claude/skills/vendor/**"
          "Changelog.md"
          "docs/developer/CommitConventions.md"
          "infra/root_chart/**"
          "infra/primordial_chart/**"
          # GENERATED by config:schema and byte-compared by config:schema:verify.
          # prettier collapses short arrays onto one line, the generator emits them
          # expanded, and the library compares bytes - so formatting this file makes its
          # own gate permanently unsatisfiable. The generator owns these bytes.
          "App/Config/settings.schema.json"
        ];
      };
      shfmt.enable = true;
    };
  };
in
(treefmt-nix.lib.evalModule pkgs fmt).config.build.wrapper
