apiVersion: v2
name: diene-xenon
description: Conditional metrics-server wrapper chart for AtomiCloud platform landscapes
type: application
version: 0.1.0
appVersion: '0.7.1'
kubeVersion: '>=1.27.0-0'
dependencies:
  - name: metrics-server
    alias: metricsServer
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metricsServer.enabled
