apiVersion: v2
name: platinum
description: AtomiCloud platform Gateway API ingress chart wrapping kgateway (element platinum)
type: application
version: 0.1.0
appVersion: 'v2.2.9'
kubeVersion: '>=1.27.0-0'
dependencies:
  - name: kgateway
    alias: upstream
    version: v2.2.9
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    condition: upstream.enabled
  - name: kgateway-crds
    version: v2.2.9
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    condition: kgatewayCrds.enabled
