---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-template-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - journals
  - notes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - journals/status
  - notes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - notes/finalizers
  verbs:
  - update
