---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - journals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - journals/status
  - notes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - notes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - sample.diene.atomi.cloud
  resources:
  - notes/finalizers
  verbs:
  - update
