---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boron-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - boron.atomi.cloud
  resources:
  - accounts
  - exposures
  - tunnels
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - boron.atomi.cloud
  resources:
  - accounts/status
  - exposures/status
  - tunnels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - boron.atomi.cloud
  resources:
  - exposures/finalizers
  - tunnels/finalizers
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
