//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAvailableVersion) DeepCopyInto(out *CloudflareAvailableVersion) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAvailableVersion.
func (in *CloudflareAvailableVersion) DeepCopy() *CloudflareAvailableVersion {
	if in == nil {
		return nil
	}
	out := new(CloudflareAvailableVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDeploy) DeepCopyInto(out *CloudflareDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDeploy.
func (in *CloudflareDeploy) DeepCopy() *CloudflareDeploy {
	if in == nil {
		return nil
	}
	out := new(CloudflareDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDeployList) DeepCopyInto(out *CloudflareDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDeployList.
func (in *CloudflareDeployList) DeepCopy() *CloudflareDeployList {
	if in == nil {
		return nil
	}
	out := new(CloudflareDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDeploySpec) DeepCopyInto(out *CloudflareDeploySpec) {
	*out = *in
	if in.DesiredVersionFrom != nil {
		in, out := &in.DesiredVersionFrom, &out.DesiredVersionFrom
		*out = new(CloudflareDesiredVersionFrom)
		**out = **in
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(CloudflareRollout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDeploySpec.
func (in *CloudflareDeploySpec) DeepCopy() *CloudflareDeploySpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDeployStatus) DeepCopyInto(out *CloudflareDeployStatus) {
	*out = *in
	if in.AvailableVersions != nil {
		in, out := &in.AvailableVersions, &out.AvailableVersions
		*out = make([]CloudflareAvailableVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(CloudflareDeploymentStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDeployStatus.
func (in *CloudflareDeployStatus) DeepCopy() *CloudflareDeployStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDeploymentStatus) DeepCopyInto(out *CloudflareDeploymentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDeploymentStatus.
func (in *CloudflareDeploymentStatus) DeepCopy() *CloudflareDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDesiredVersionFrom) DeepCopyInto(out *CloudflareDesiredVersionFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDesiredVersionFrom.
func (in *CloudflareDesiredVersionFrom) DeepCopy() *CloudflareDesiredVersionFrom {
	if in == nil {
		return nil
	}
	out := new(CloudflareDesiredVersionFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRollout) DeepCopyInto(out *CloudflareRollout) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]CloudflareRolloutStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRollout.
func (in *CloudflareRollout) DeepCopy() *CloudflareRollout {
	if in == nil {
		return nil
	}
	out := new(CloudflareRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRolloutStep) DeepCopyInto(out *CloudflareRolloutStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRolloutStep.
func (in *CloudflareRolloutStep) DeepCopy() *CloudflareRolloutStep {
	if in == nil {
		return nil
	}
	out := new(CloudflareRolloutStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegistration) DeepCopyInto(out *ClusterRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegistration.
func (in *ClusterRegistration) DeepCopy() *ClusterRegistration {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegistrationList) DeepCopyInto(out *ClusterRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegistrationList.
func (in *ClusterRegistrationList) DeepCopy() *ClusterRegistrationList {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegistrationSpec) DeepCopyInto(out *ClusterRegistrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegistrationSpec.
func (in *ClusterRegistrationSpec) DeepCopy() *ClusterRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRegistrationStatus) DeepCopyInto(out *ClusterRegistrationStatus) {
	*out = *in
	if in.LBIPs != nil {
		in, out := &in.LBIPs, &out.LBIPs
		*out = make([]LoadBalancerIP, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRegistrationStatus.
func (in *ClusterRegistrationStatus) DeepCopy() *ClusterRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decommission) DeepCopyInto(out *Decommission) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decommission.
func (in *Decommission) DeepCopy() *Decommission {
	if in == nil {
		return nil
	}
	out := new(Decommission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Decommission) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecommissionList) DeepCopyInto(out *DecommissionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Decommission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecommissionList.
func (in *DecommissionList) DeepCopy() *DecommissionList {
	if in == nil {
		return nil
	}
	out := new(DecommissionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecommissionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecommissionSpec) DeepCopyInto(out *DecommissionSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecommissionSpec.
func (in *DecommissionSpec) DeepCopy() *DecommissionSpec {
	if in == nil {
		return nil
	}
	out := new(DecommissionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecommissionStatus) DeepCopyInto(out *DecommissionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecommissionStatus.
func (in *DecommissionStatus) DeepCopy() *DecommissionStatus {
	if in == nil {
		return nil
	}
	out := new(DecommissionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecommissionTargetReference) DeepCopyInto(out *DecommissionTargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecommissionTargetReference.
func (in *DecommissionTargetReference) DeepCopy() *DecommissionTargetReference {
	if in == nil {
		return nil
	}
	out := new(DecommissionTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyAccountSelector) DeepCopyInto(out *DependencyAccountSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyAccountSelector.
func (in *DependencyAccountSelector) DeepCopy() *DependencyAccountSelector {
	if in == nil {
		return nil
	}
	out := new(DependencyAccountSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyAutoscale) DeepCopyInto(out *DependencyAutoscale) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyAutoscale.
func (in *DependencyAutoscale) DeepCopy() *DependencyAutoscale {
	if in == nil {
		return nil
	}
	out := new(DependencyAutoscale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBackup) DeepCopyInto(out *DependencyBackup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBackup.
func (in *DependencyBackup) DeepCopy() *DependencyBackup {
	if in == nil {
		return nil
	}
	out := new(DependencyBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyDeletionPolicy) DeepCopyInto(out *DependencyDeletionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyDeletionPolicy.
func (in *DependencyDeletionPolicy) DeepCopy() *DependencyDeletionPolicy {
	if in == nil {
		return nil
	}
	out := new(DependencyDeletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyEngine) DeepCopyInto(out *DependencyEngine) {
	*out = *in
	if in.Neon != nil {
		in, out := &in.Neon, &out.Neon
		*out = new(NeonDependencyEngine)
		(*in).DeepCopyInto(*out)
	}
	if in.NeonFork != nil {
		in, out := &in.NeonFork, &out.NeonFork
		*out = new(ForkDependencyEngine)
		**out = **in
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.Upstash != nil {
		in, out := &in.Upstash, &out.Upstash
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.UpstashFork != nil {
		in, out := &in.UpstashFork, &out.UpstashFork
		*out = new(ForkDependencyEngine)
		**out = **in
	}
	if in.Dragonfly != nil {
		in, out := &in.Dragonfly, &out.Dragonfly
		*out = new(DragonflyDependencyEngine)
		**out = **in
	}
	if in.Tigris != nil {
		in, out := &in.Tigris, &out.Tigris
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.TigrisFork != nil {
		in, out := &in.TigrisFork, &out.TigrisFork
		*out = new(ForkDependencyEngine)
		**out = **in
	}
	if in.R2 != nil {
		in, out := &in.R2, &out.R2
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.SES != nil {
		in, out := &in.SES, &out.SES
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.CFEmailSending != nil {
		in, out := &in.CFEmailSending, &out.CFEmailSending
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
	if in.Mailpit != nil {
		in, out := &in.Mailpit, &out.Mailpit
		*out = new(EmptyDependencyEngine)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyEngine.
func (in *DependencyEngine) DeepCopy() *DependencyEngine {
	if in == nil {
		return nil
	}
	out := new(DependencyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyParentCoordinate) DeepCopyInto(out *DependencyParentCoordinate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyParentCoordinate.
func (in *DependencyParentCoordinate) DeepCopy() *DependencyParentCoordinate {
	if in == nil {
		return nil
	}
	out := new(DependencyParentCoordinate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyPlacement) DeepCopyInto(out *DependencyPlacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyPlacement.
func (in *DependencyPlacement) DeepCopy() *DependencyPlacement {
	if in == nil {
		return nil
	}
	out := new(DependencyPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DragonflyDependencyEngine) DeepCopyInto(out *DragonflyDependencyEngine) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DragonflyDependencyEngine.
func (in *DragonflyDependencyEngine) DeepCopy() *DragonflyDependencyEngine {
	if in == nil {
		return nil
	}
	out := new(DragonflyDependencyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmptyDependencyEngine) DeepCopyInto(out *EmptyDependencyEngine) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmptyDependencyEngine.
func (in *EmptyDependencyEngine) DeepCopy() *EmptyDependencyEngine {
	if in == nil {
		return nil
	}
	out := new(EmptyDependencyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkDependencyEngine) DeepCopyInto(out *ForkDependencyEngine) {
	*out = *in
	out.Parent = in.Parent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkDependencyEngine.
func (in *ForkDependencyEngine) DeepCopy() *ForkDependencyEngine {
	if in == nil {
		return nil
	}
	out := new(ForkDependencyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Landscape) DeepCopyInto(out *Landscape) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Landscape.
func (in *Landscape) DeepCopy() *Landscape {
	if in == nil {
		return nil
	}
	out := new(Landscape)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Landscape) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeList) DeepCopyInto(out *LandscapeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Landscape, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeList.
func (in *LandscapeList) DeepCopy() *LandscapeList {
	if in == nil {
		return nil
	}
	out := new(LandscapeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscapeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeSpec) DeepCopyInto(out *LandscapeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeSpec.
func (in *LandscapeSpec) DeepCopy() *LandscapeSpec {
	if in == nil {
		return nil
	}
	out := new(LandscapeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeStatus) DeepCopyInto(out *LandscapeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeStatus.
func (in *LandscapeStatus) DeepCopy() *LandscapeStatus {
	if in == nil {
		return nil
	}
	out := new(LandscapeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerIP) DeepCopyInto(out *LoadBalancerIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerIP.
func (in *LoadBalancerIP) DeepCopy() *LoadBalancerIP {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeonDependencyEngine) DeepCopyInto(out *NeonDependencyEngine) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(DependencyAutoscale)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeonDependencyEngine.
func (in *NeonDependencyEngine) DeepCopy() *NeonDependencyEngine {
	if in == nil {
		return nil
	}
	out := new(NeonDependencyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStage) DeepCopyInto(out *PipelineStage) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStage.
func (in *PipelineStage) DeepCopy() *PipelineStage {
	if in == nil {
		return nil
	}
	out := new(PipelineStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Platform) DeepCopyInto(out *Platform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Platform.
func (in *Platform) DeepCopy() *Platform {
	if in == nil {
		return nil
	}
	out := new(Platform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Platform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependency) DeepCopyInto(out *PlatformDependency) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependency.
func (in *PlatformDependency) DeepCopy() *PlatformDependency {
	if in == nil {
		return nil
	}
	out := new(PlatformDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformDependency) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencyForkStatus) DeepCopyInto(out *PlatformDependencyForkStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencyForkStatus.
func (in *PlatformDependencyForkStatus) DeepCopy() *PlatformDependencyForkStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencyForkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencyList) DeepCopyInto(out *PlatformDependencyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencyList.
func (in *PlatformDependencyList) DeepCopy() *PlatformDependencyList {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformDependencyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencyModuleSpec) DeepCopyInto(out *PlatformDependencyModuleSpec) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(DependencyAccountSelector)
		**out = **in
	}
	out.CPU = in.CPU
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(DependencyBackup)
		**out = **in
	}
	in.Engine.DeepCopyInto(&out.Engine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencyModuleSpec.
func (in *PlatformDependencyModuleSpec) DeepCopy() *PlatformDependencyModuleSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencyModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencyModuleStatus) DeepCopyInto(out *PlatformDependencyModuleStatus) {
	*out = *in
	if in.Fork != nil {
		in, out := &in.Fork, &out.Fork
		*out = new(PlatformDependencyForkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencyModuleStatus.
func (in *PlatformDependencyModuleStatus) DeepCopy() *PlatformDependencyModuleStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencyModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencySpec) DeepCopyInto(out *PlatformDependencySpec) {
	*out = *in
	out.Placement = in.Placement
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = make(map[string]PlatformDependencyModuleSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.KV != nil {
		in, out := &in.KV, &out.KV
		*out = make(map[string]PlatformDependencyModuleSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = make(map[string]PlatformDependencyModuleSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = make(map[string]PlatformDependencyModuleSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = make(map[string]PlatformDependencyModuleSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.DeletionPolicy = in.DeletionPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencySpec.
func (in *PlatformDependencySpec) DeepCopy() *PlatformDependencySpec {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDependencyStatus) DeepCopyInto(out *PlatformDependencyStatus) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make(map[string]PlatformDependencyModuleStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDependencyStatus.
func (in *PlatformDependencyStatus) DeepCopy() *PlatformDependencyStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformDependencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformInfisicalSpec) DeepCopyInto(out *PlatformInfisicalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformInfisicalSpec.
func (in *PlatformInfisicalSpec) DeepCopy() *PlatformInfisicalSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformInfisicalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformList) DeepCopyInto(out *PlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Platform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformList.
func (in *PlatformList) DeepCopy() *PlatformList {
	if in == nil {
		return nil
	}
	out := new(PlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformPipelineSpec) DeepCopyInto(out *PlatformPipelineSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]PipelineStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformPipelineSpec.
func (in *PlatformPipelineSpec) DeepCopy() *PlatformPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSoSSpec) DeepCopyInto(out *PlatformSoSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSoSSpec.
func (in *PlatformSoSSpec) DeepCopy() *PlatformSoSSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformSoSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSpec) DeepCopyInto(out *PlatformSpec) {
	*out = *in
	out.Infisical = in.Infisical
	out.SoS = in.SoS
	in.Pipeline.DeepCopyInto(&out.Pipeline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSpec.
func (in *PlatformSpec) DeepCopy() *PlatformSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformStatus) DeepCopyInto(out *PlatformStatus) {
	*out = *in
	if in.Belt != nil {
		in, out := &in.Belt, &out.Belt
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformStatus.
func (in *PlatformStatus) DeepCopy() *PlatformStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccount) DeepCopyInto(out *ProviderAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccount.
func (in *ProviderAccount) DeepCopy() *ProviderAccount {
	if in == nil {
		return nil
	}
	out := new(ProviderAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccountList) DeepCopyInto(out *ProviderAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccountList.
func (in *ProviderAccountList) DeepCopy() *ProviderAccountList {
	if in == nil {
		return nil
	}
	out := new(ProviderAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccountQuotaSpec) DeepCopyInto(out *ProviderAccountQuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccountQuotaSpec.
func (in *ProviderAccountQuotaSpec) DeepCopy() *ProviderAccountQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAccountQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccountSpec) DeepCopyInto(out *ProviderAccountSpec) {
	*out = *in
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make([]ProviderAccountQuotaSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccountSpec.
func (in *ProviderAccountSpec) DeepCopy() *ProviderAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAccountStatus) DeepCopyInto(out *ProviderAccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAccountStatus.
func (in *ProviderAccountStatus) DeepCopy() *ProviderAccountStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscape) DeepCopyInto(out *VirtualLandscape) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscape.
func (in *VirtualLandscape) DeepCopy() *VirtualLandscape {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscape)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualLandscape) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeList) DeepCopyInto(out *VirtualLandscapeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualLandscape, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeList.
func (in *VirtualLandscapeList) DeepCopy() *VirtualLandscapeList {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualLandscapeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeService) DeepCopyInto(out *VirtualLandscapeService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeService.
func (in *VirtualLandscapeService) DeepCopy() *VirtualLandscapeService {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualLandscapeService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeServiceList) DeepCopyInto(out *VirtualLandscapeServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualLandscapeService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeServiceList.
func (in *VirtualLandscapeServiceList) DeepCopy() *VirtualLandscapeServiceList {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualLandscapeServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeServiceModuleStatus) DeepCopyInto(out *VirtualLandscapeServiceModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeServiceModuleStatus.
func (in *VirtualLandscapeServiceModuleStatus) DeepCopy() *VirtualLandscapeServiceModuleStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeServiceModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeServiceSpec) DeepCopyInto(out *VirtualLandscapeServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeServiceSpec.
func (in *VirtualLandscapeServiceSpec) DeepCopy() *VirtualLandscapeServiceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeServiceStatus) DeepCopyInto(out *VirtualLandscapeServiceStatus) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make(map[string]VirtualLandscapeServiceModuleStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeServiceStatus.
func (in *VirtualLandscapeServiceStatus) DeepCopy() *VirtualLandscapeServiceStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeSpec) DeepCopyInto(out *VirtualLandscapeSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeSpec.
func (in *VirtualLandscapeSpec) DeepCopy() *VirtualLandscapeSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualLandscapeStatus) DeepCopyInto(out *VirtualLandscapeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualLandscapeStatus.
func (in *VirtualLandscapeStatus) DeepCopy() *VirtualLandscapeStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualLandscapeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookArchive) DeepCopyInto(out *WebhookArchive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookArchive.
func (in *WebhookArchive) DeepCopy() *WebhookArchive {
	if in == nil {
		return nil
	}
	out := new(WebhookArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookBackoff) DeepCopyInto(out *WebhookBackoff) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookBackoff.
func (in *WebhookBackoff) DeepCopy() *WebhookBackoff {
	if in == nil {
		return nil
	}
	out := new(WebhookBackoff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookCircuitBreaker) DeepCopyInto(out *WebhookCircuitBreaker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookCircuitBreaker.
func (in *WebhookCircuitBreaker) DeepCopy() *WebhookCircuitBreaker {
	if in == nil {
		return nil
	}
	out := new(WebhookCircuitBreaker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEngine) DeepCopyInto(out *WebhookEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEngine.
func (in *WebhookEngine) DeepCopy() *WebhookEngine {
	if in == nil {
		return nil
	}
	out := new(WebhookEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEngineHome) DeepCopyInto(out *WebhookEngineHome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEngineHome.
func (in *WebhookEngineHome) DeepCopy() *WebhookEngineHome {
	if in == nil {
		return nil
	}
	out := new(WebhookEngineHome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEngineList) DeepCopyInto(out *WebhookEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEngineList.
func (in *WebhookEngineList) DeepCopy() *WebhookEngineList {
	if in == nil {
		return nil
	}
	out := new(WebhookEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEngineSpec) DeepCopyInto(out *WebhookEngineSpec) {
	*out = *in
	out.Home = in.Home
	out.Retention = in.Retention
	out.Backoff = in.Backoff
	out.CircuitBreaker = in.CircuitBreaker
	out.Quotas = in.Quotas
	if in.CustomDomains != nil {
		in, out := &in.CustomDomains, &out.CustomDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEngineSpec.
func (in *WebhookEngineSpec) DeepCopy() *WebhookEngineSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEngineStatus) DeepCopyInto(out *WebhookEngineStatus) {
	*out = *in
	if in.Landscapes != nil {
		in, out := &in.Landscapes, &out.Landscapes
		*out = make(map[string]WebhookLandscapeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make(map[string]WebhookProviderStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEngineStatus.
func (in *WebhookEngineStatus) DeepCopy() *WebhookEngineStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookEngineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookLandscapeStatus) DeepCopyInto(out *WebhookLandscapeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookLandscapeStatus.
func (in *WebhookLandscapeStatus) DeepCopy() *WebhookLandscapeStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookLandscapeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookProviderStatus) DeepCopyInto(out *WebhookProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookProviderStatus.
func (in *WebhookProviderStatus) DeepCopy() *WebhookProviderStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookQuotas) DeepCopyInto(out *WebhookQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookQuotas.
func (in *WebhookQuotas) DeepCopy() *WebhookQuotas {
	if in == nil {
		return nil
	}
	out := new(WebhookQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRetention) DeepCopyInto(out *WebhookRetention) {
	*out = *in
	out.Archive = in.Archive
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRetention.
func (in *WebhookRetention) DeepCopy() *WebhookRetention {
	if in == nil {
		return nil
	}
	out := new(WebhookRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRoute) DeepCopyInto(out *WebhookRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRoute.
func (in *WebhookRoute) DeepCopy() *WebhookRoute {
	if in == nil {
		return nil
	}
	out := new(WebhookRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRouteList) DeepCopyInto(out *WebhookRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRouteList.
func (in *WebhookRouteList) DeepCopy() *WebhookRouteList {
	if in == nil {
		return nil
	}
	out := new(WebhookRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRouteSpec) DeepCopyInto(out *WebhookRouteSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRouteSpec.
func (in *WebhookRouteSpec) DeepCopy() *WebhookRouteSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRouteStatus) DeepCopyInto(out *WebhookRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRouteStatus.
func (in *WebhookRouteStatus) DeepCopy() *WebhookRouteStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRouteTarget) DeepCopyInto(out *WebhookRouteTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRouteTarget.
func (in *WebhookRouteTarget) DeepCopy() *WebhookRouteTarget {
	if in == nil {
		return nil
	}
	out := new(WebhookRouteTarget)
	in.DeepCopyInto(out)
	return out
}
