name: diene_config
description: Layered, schema-composed configuration for Dart and Flutter applications.
version: 0.1.0
repository: https://github.com/AtomiCloud/diene.dart_config
issue_tracker: https://github.com/AtomiCloud/diene.dart_config/issues
topics:
  - configuration
  - yaml
  - flutter

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.3

dev_dependencies:
  crypto: ^3.0.7
  lints: ^6.0.0
  pana: ^0.23.14
  test: ^1.26.3
