swagger_parser:
  schema_path: openapi/service.openapi.yaml
  output_directory: lib/generated/service
  language: dart
  json_serializer: json_serializable
  root_client: false
  put_clients_in_folder: true
  enums_to_json: true
  unknown_enum_value: true
  mark_files_as_generated: true
