{{/* Stable chart identity. */}}
{{- define "sulfur.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* The one and only service-tree label/annotation prefix. */}}
{{- define "sulfur.labelPrefix" -}}
{{- required "labelPrefix is required" .Values.labelPrefix | trimSuffix "/" -}}
{{- end -}}

{{/* Validate the base LPSM projection. Platform must equal the release namespace,
     and the render-time identity layer (upstream.global.commonLabels, generated by
     scripts/local/gen-identity-values.sh) must mirror the validated platform value.
     Side-effect only: every required lookup is discarded so the helper emits no text
     and can be included by a zero-resource guard template. */}}
{{- define "sulfur.validateServiceTree" -}}
{{- $platform := required "serviceTree.platform is required" .Values.serviceTree.platform -}}
{{- $_ := required "serviceTree.service is required" .Values.serviceTree.service -}}
{{- $_ := required "serviceTree.module is required" .Values.serviceTree.module -}}
{{- $_ := required "serviceTree.layer is required" .Values.serviceTree.layer -}}
{{- if ne $platform .Release.Namespace -}}
{{- fail (printf "serviceTree.platform %q must equal release namespace %q" $platform .Release.Namespace) -}}
{{- end -}}
{{- $prefix := include "sulfur.labelPrefix" . -}}
{{- $labels := dig "global" "commonLabels" dict .Values.upstream -}}
{{- $mirror := index $labels (printf "%s/platform" $prefix) -}}
{{- if ne $mirror $platform -}}
{{- fail (printf "upstream.global.commonLabels %q/platform %q must equal serviceTree.platform %q — render with the identity layer from scripts/local/gen-identity-values.sh" $prefix $mirror $platform) -}}
{{- end -}}
{{- end -}}
