{{- include "diene-helm-wrapper.validateServiceTree" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diene-helm-wrapper.resourceName" (dict "root" . "token" "config") }}
  labels:
    {{- include "diene-helm-wrapper.labels" . | nindent 4 }}
  annotations:
    {{- include "diene-helm-wrapper.annotations" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "files/config/*.yaml" }}
  {{ base $path }}: |-
    {{- $bytes | toString | nindent 4 }}
  {{- end }}
