{{- if .Values.secret.enabled -}}
{{- include "diene-helm-wrapper.validateServiceTree" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "diene-helm-wrapper.resourceName" (dict "root" . "token" "secrets") }}
  labels:
    {{- include "diene-helm-wrapper.labels" . | nindent 4 }}
  annotations:
    {{- include "diene-helm-wrapper.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: {{ .Values.secret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secret.store.kind }}
    name: {{ .Values.secret.store.name }}
  target:
    name: {{ .Values.serviceTree.service }}
    creationPolicy: Owner
  dataFrom:
    - find:
        path: {{ .Values.secret.sharedFolder }}
      rewrite:
        - regexp:
            source: '(.*)'
            target: 'SHARED_$1'
    - find:
        path: {{ .Values.secret.serviceFolder }}
      rewrite:
        - regexp:
            source: '(.*)'
            target: '{{ upper .Values.serviceTree.service }}_$1'
{{- end }}
