{{- include "zinc.validateServiceTree" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "zinc.resourceName" (dict "root" . "token" "cloudflare") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zinc.labels" . | nindent 4 }}
  annotations:
    {{- include "zinc.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: {{ .Values.secret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secret.store.kind }}
    name: {{ .Values.secret.store.name }}
  target:
    name: {{ .Values.issuer.cloudflare.apiTokenSecretRef.name }}
    creationPolicy: Owner
  dataFrom:
    - find:
        path: {{ .Values.secret.folder }}
      rewrite:
        - regexp:
            source: '(.*)'
            target: 'SHARED_$1'
