# ### workspace-helm
# #### source: workspace
version: '3'

vars:
  CHART: infra/root_chart

tasks:
  deps:
    desc: Build chart dependencies
    cmds:
      - helm dependency build {{.CHART}}

  lint:
    desc: Lint the root chart
    cmds:
      - helm lint {{.CHART}}

  template:
    desc: Render the root chart
    cmds:
      - helm template operator-template {{.CHART}} {{.CLI_ARGS}}

  debug:
    desc: Render the root chart with debug output
    cmds:
      - helm template operator-template {{.CHART}} --debug {{.CLI_ARGS}}
