version: '3'

tasks:
  debug:
    desc: Render the stacked chart with debug output
    dir: '{{.ROOT_DIR}}/chart'
    cmds:
      - '{{.ROOT_DIR}}/scripts/local/vendor-chart-config.sh'
      - helm dependency build
      - helm template {{.RELEASE_NAME}} . --namespace {{.NAMESPACE}} --debug --values values.{{.LANDSCAPE}}.yaml --values values.{{.CLUSTER}}.yaml {{.CLI_ARGS}}

  template:
    desc: Render the stacked chart
    dir: '{{.ROOT_DIR}}/chart'
    cmds:
      - '{{.ROOT_DIR}}/scripts/local/vendor-chart-config.sh'
      - helm dependency build
      - helm template {{.RELEASE_NAME}} . --namespace {{.NAMESPACE}} --values values.{{.LANDSCAPE}}.yaml --values values.{{.CLUSTER}}.yaml {{.CLI_ARGS}}

  install:
    desc: Install or upgrade the stacked chart
    dir: '{{.ROOT_DIR}}/chart'
    cmds:
      - '{{.ROOT_DIR}}/scripts/local/vendor-chart-config.sh'
      - helm dependency build
      - helm upgrade --install {{.RELEASE_NAME}} . --namespace {{.NAMESPACE}} --create-namespace --values values.{{.LANDSCAPE}}.yaml --values values.{{.CLUSTER}}.yaml --wait --timeout 5m {{.CLI_ARGS}}

  remove:
    desc: Remove the installed release
    cmds:
      - helm uninstall {{.RELEASE_NAME}} --namespace {{.NAMESPACE}} {{.CLI_ARGS}}
