# ### workspace-docker
# #### source: workspace
version: '3'

vars:
  IMAGE: boron:local

tasks:
  build:
    desc: Build the local Go image
    cmds:
      - docker build -f infra/Dockerfile -t {{.IMAGE}}{{if .CLI_ARGS}}-{{.CLI_ARGS}}{{end}} .

  run:
    desc: Run the local Go image
    cmds:
      - docker run --rm {{.IMAGE}}{{if .CLI_ARGS}}-{{.CLI_ARGS}}{{end}}

  clean:
    desc: Remove the local Go image
    cmds:
      - docker image rm {{.IMAGE}}{{if .CLI_ARGS}}-{{.CLI_ARGS}}{{end}} || true
