apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator-template.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator-template.labels" . | nindent 4 }}
