apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator-template.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator-template.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "operator-template.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
