# Source: vanadium/templates/policies.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: vanadium-requireresources
  labels:
    helm.sh/chart: vanadium-0.1.0
    app.kubernetes.io/name: vanadium
    app.kubernetes.io/instance: vanadium
    atomi.cloud/cluster: "lapras"
    atomi.cloud/landscape: "example"
    atomi.cloud/layer: "0"
    atomi.cloud/module: "admission"
    atomi.cloud/platform: "fleet"
    atomi.cloud/service: "vanadium"
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    atomi.cloud/cluster: "lapras"
    atomi.cloud/landscape: "example"
    atomi.cloud/layer: "0"
    atomi.cloud/module: "admission"
    atomi.cloud/platform: "fleet"
    atomi.cloud/service: "vanadium"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [apps, batch]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [deployments, statefulsets, daemonsets, jobs]
  validations:
    - expression: |-

        object.spec.template.spec.containers.all(c,
          has(c.resources) && has(c.resources.requests) && has(c.resources.limits) &&
          has(c.resources.requests.cpu) && has(c.resources.requests.memory) &&
          has(c.resources.limits.cpu) && has(c.resources.limits.memory)) &&
        (!has(object.spec.template.spec.initContainers) || object.spec.template.spec.initContainers.all(c,
          has(c.resources) && has(c.resources.requests) && has(c.resources.limits) &&
          has(c.resources.requests.cpu) && has(c.resources.requests.memory) &&
          has(c.resources.limits.cpu) && has(c.resources.limits.memory)))
      message: Every container must declare CPU and memory requests and limits.
