// GENERATED by tool/gen_c0_projection.dart from c0-fixtures-r2 — DO NOT EDIT.
library;

/// One immutable prose-source pin carried by the generated C0 projection.
final class C0ProblemSourcePin {
  const C0ProblemSourcePin({
    required this.path,
    required this.sha256,
    this.note,
  });
  final String path;
  final String sha256;
  final String? note;
}

/// Authenticated identity of the neutral C0 release used for this projection.
final class C0ProblemReleaseProvenance {
  const C0ProblemReleaseProvenance({
    required this.releaseId,
    required this.contractVersion,
    required this.releaseDigest,
    required this.c0ProseSource,
    required this.secondarySources,
    required this.formatterPolicyPath,
    required this.formatterPolicySha256,
    required this.prettierExcludedPaths,
  });
  final String releaseId;
  final int contractVersion;
  final String releaseDigest;
  final C0ProblemSourcePin c0ProseSource;
  final List<C0ProblemSourcePin> secondarySources;
  final String formatterPolicyPath;
  final String formatterPolicySha256;
  final List<String> prettierExcludedPaths;
}

/// Generated C0 §2/§14 Problem vectors from the neutral release.
final class C0ProblemContract {
  const C0ProblemContract({
    required this.provenance,
    required this.c0Sections,
    required this.rfc9457Members,
    required this.extensions,
    required this.typeUriTemplate,
    required this.typeUri,
    required this.envelopes,
    required this.catalogEntry,
  });
  final C0ProblemReleaseProvenance provenance;
  final List<String> c0Sections;
  final List<String> rfc9457Members;
  final List<String> extensions;
  final String typeUriTemplate;
  final Map<String, Object?> typeUri;
  final Map<String, Object?> envelopes;
  final Map<String, Object?> catalogEntry;
}

/// The generated projection of c0-fixtures-r2.
const C0ProblemContract c0ProblemContract = C0ProblemContract(
  provenance: C0ProblemReleaseProvenance(
    releaseId: "c0-fixtures-r2",
    contractVersion: 2,
    releaseDigest:
        "0e64439c681a22fb4f02285c082ed8ffb7b465e732fde4e49757e9e3c9a5783e",
    c0ProseSource: C0ProblemSourcePin(
      path: "goals/c0-contracts.md",
      sha256:
          "7dd7a06279f3078a5e195d4103d01ce9fd1b30a7d88178ec37c3e6f0465c7101",
      note:
          "workspace overlay pinned by SHA-256; r2 verbatim excerpt set committed under contracts/c0/provenance",
    ),
    secondarySources: <C0ProblemSourcePin>[
      C0ProblemSourcePin(
        path: "goals/lib/dart-family.md",
        sha256:
            "ece72edbb18e2c45f6f16e3a4da2172862f7b044d4218292f90e5219da0b5bd6",
      ),
      C0ProblemSourcePin(
        path: "goals/lib/result-deep-dive.md",
        sha256:
            "68e9ec021b3c286fa377bfb8ee02373cfab3146d5c6f43ce9d0085c27fefb164",
      ),
    ],
    formatterPolicyPath: ".prettierignore",
    formatterPolicySha256:
        "a5163b3ccf4e9da2956f3ed0f6866569fc34164050ca55e3e805ee1cc9a5bb02",
    prettierExcludedPaths: <String>[
      "/contracts/c0/RELEASE.json",
      "/contracts/c0/cases/config.json",
      "/contracts/c0/cases/identity.json",
      "/contracts/c0/cases/problem.json",
      "/contracts/c0/cases/result-wire.json",
      "/contracts/c0/provenance/app-handoff.md",
      "/contracts/c0/provenance/config-precedence.md",
      "/contracts/c0/provenance/edge-docs.md",
      "/contracts/c0/provenance/home-claim.md",
      "/contracts/c0/provenance/onboarding-claim.md",
      "/contracts/c0/provenance/problem-catalog.md",
      "/contracts/c0/provenance/problem-schema.md",
      "/contracts/c0/provenance/result-semantics.md",
      "/contracts/c0/provenance/token-lifetimes.md",
      "/test/fixtures/c0/catalog-entry.json",
      "/test/fixtures/c0/config.json",
      "/test/fixtures/c0/envelope.json",
      "/test/fixtures/c0/identity.json",
      "/test/fixtures/c0/problem-envelope.json",
      "/test/fixtures/c0/result-wire.json",
      "/test/fixtures/c0/type-uri.json",
    ],
  ),
  c0Sections: <String>["§2 Problem schema", "§14 Problem catalog schema"],
  rfc9457Members: <String>["type", "title", "status", "detail", "instance"],
  extensions: <String>["data", "recoverable"],
  typeUriTemplate:
      "{scheme}://{host}/docs/{landscape}/{platform}/{service}/{module}/{version}/{id}",
  typeUri: <String, Object?>{
    "invalid": <Object?>[],
    "valid": <Object?>[
      <String, Object?>{
        "expectedTypeUri":
            "https://docs.raichu.cluster.atomi.cloud/docs/raichu/dotnet/user/api/v1/entity-not-found",
        "segments": <String, Object?>{
          "host": "docs.raichu.cluster.atomi.cloud",
          "id": "entity-not-found",
          "landscape": "raichu",
          "module": "api",
          "platform": "dotnet",
          "scheme": "https",
          "service": "user",
          "version": "v1",
        },
      },
    ],
  },
  envelopes: <String, Object?>{
    "invalid": <Object?>[],
    "valid": <Object?>[
      <String, Object?>{
        "data": <String, Object?>{"id": 42, "resource": "user"},
        "detail": "User 42 does not exist",
        "instance": "/user/42",
        "recoverable": false,
        "status": 404,
        "title": "Entity not found",
        "type":
            "https://docs.raichu.cluster.atomi.cloud/docs/raichu/dotnet/user/api/v1/entity-not-found",
      },
    ],
  },
  catalogEntry: <String, Object?>{
    "samples": <Object?>[
      <String, Object?>{
        "data": <String, Object?>{
          "properties": <String, Object?>{
            "fields": <String, Object?>{"type": "array"},
          },
          "type": "object",
        },
        "endpoints": <Object?>[
          <String, Object?>{"method": "POST", "path": "/user"},
        ],
        "id": "validation-error",
        "recoverable": true,
        "status": 400,
        "title": "Validation error",
        "type":
            "https://docs.raichu.cluster.atomi.cloud/docs/raichu/dotnet/user/api/v1/validation-error",
      },
    ],
    "shape": <Object?>[
      "id",
      "type",
      "title",
      "status",
      "recoverable",
      "data",
      "endpoints",
    ],
  },
);
