import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:diene_interfaces/diene_interfaces.dart';
import 'package:diene_interfaces/test_helper.dart';
import 'package:diene_problems/diene_problems.dart';
import 'package:diene_result/diene_result.dart';
import 'package:diene_result/test_helper.dart';
import 'package:test/test.dart';

/// Frozen C0 (`c0-fixtures-r2`) §2 projection, generated by
/// `tool/gen_c0_projection.dart` from `contracts/c0/cases/problem.json`.
const String _fixturePath = 'test/fixtures/c0/problem-envelope.json';
const String _checksumPath = 'test/fixtures/c0/SHA256SUMS';

Map<String, Object?> _object(Object? value) =>
    (value! as Map<Object?, Object?>).cast<String, Object?>();

List<String> _strings(Object? value) =>
    (value! as List<Object?>).cast<String>();

/// Turns the frozen `{placeholder}` template into an anchored path matcher.
///
/// Derived from the fixture rather than hard-coded, so a template change in a
/// future C0 release re-shapes the assertion instead of silently passing.
String _templatePattern(String template) {
  final StringBuffer pattern = StringBuffer('^');
  int index = 0;
  for (final RegExpMatch match in RegExp(
    r'\{[a-zA-Z]+\}',
  ).allMatches(template)) {
    pattern
      ..write(RegExp.escape(template.substring(index, match.start)))
      ..write(r'[^/]+');
    index = match.end;
  }
  pattern
    ..write(RegExp.escape(template.substring(index)))
    ..write(r'$');
  return pattern.toString();
}

void main() {
  final String rendered = File(_fixturePath).readAsStringSync();
  final Map<String, Object?> fixture = _object(jsonDecode(rendered));

  group('frozen C0 projection integrity', () {
    test('the projected bytes match the recorded digest', () {
      // Arrange.
      final String recorded = File(_checksumPath).readAsStringSync();

      // Act.
      final String actual =
          '${sha256.convert(utf8.encode(rendered))}  problem-envelope.json\n';

      // Assert.
      expect(actual, recorded);
    });

    test('the projection names the frozen release it came from', () {
      // Arrange.
      final Map<String, Object?> generated = _object(fixture[r'$generated']);

      // Act.
      final Object? releaseId = generated['releaseId'];

      // Assert.
      expect(releaseId, 'c0-fixtures-r2');
      expect(generated['sourceCase'], 'contracts/c0/cases/problem.json');
      expect(generated['domain'], 'problem');
    });
  });

  group('C0 §2 type-URI template', () {
    test('the single builder reproduces the frozen worked example', () {
      // Arrange.
      final Map<String, Object?> example = _object(
        (_object(fixture['typeUri'])['valid']! as List<Object?>).single,
      );
      final Map<String, Object?> segments = _object(example['segments']);
      final ErrorPortal portal = ErrorPortal(
        scheme: segments['scheme']! as String,
        host: segments['host']! as String,
        landscape: segments['landscape']! as String,
        platform: segments['platform']! as String,
        service: segments['service']! as String,
        module: segments['module']! as String,
      );

      // Act.
      //
      // R-E14 WIRE-ID CONTRACT VARIANCE. The frozen release `c0-fixtures-r2`
      // still SAMPLES kebab ids (`entity-not-found`) while R-E14 amended C0 so
      // the WIRE id is snake_case — the spelling the published
      // `problemTypeUri` builder enforces with `^[a-z][a-z0-9_]*$`. Feeding the
      // frozen sample in unmodified therefore throws
      // `InvalidProblemTypeSegmentError`. Normalize with the release owner's own
      // published helper `r14WireId`; this leaf NEVER rewrites the frozen
      // release bytes. A corrected fixture round (r3) is owed at the release
      // owner under R-E8a — fixed once there, inherited by merge. When it lands,
      // the variance group below fails and this normalization is deleted.
      // Follows the lead's ratified 2026-07-26 disposition already applied by
      // the published sibling `lib/dart/problems`.
      final String frozenId = segments['id']! as String;
      final String built = problemTypeUri(
        portal: portal,
        version: segments['version']! as String,
        id: r14WireId(frozenId),
      );

      // Assert. Only the id SEGMENT is normalized, never the whole URI, so a
      // hyphen anywhere else in the template would still be a real failure.
      expect(
        built,
        (example['expectedTypeUri']! as String).replaceAll(
          '/$frozenId',
          '/${r14WireId(frozenId)}',
        ),
      );
    });

    test('every seam failure type URI satisfies the frozen template', () {
      // Arrange.
      final String template = fixture['typeUriTemplate']! as String;
      final RegExp shape = RegExp(_templatePattern(template));

      // Act.
      final List<String> uris = <String>[
        for (final PortName port in PortName.values)
          for (final PortErrorCode code in PortErrorCode.values)
            portProblem(
              port: port,
              code: code,
              operation: 'probe',
              message: 'probe',
            ).type,
      ];

      // Assert.
      expect(
        uris,
        hasLength(PortName.values.length * PortErrorCode.values.length),
      );
      for (final String uri in uris) {
        expect(shape.hasMatch(uri), isTrue, reason: uri);
      }
    });

    test(
      'the type URI encodes the seam, the code, and the contract version',
      () {
        // Arrange & Act.
        final Problem problem = portProblem(
          port: PortName.vfs,
          code: PortErrorCode.notFound,
          operation: 'readText',
          message: 'Path not found',
        );

        // Assert.
        expect(
          problem.type,
          endsWith('/$interfacesProblemVersion/vfs_not_found'),
        );
      },
    );
  });

  group('C0 §2 envelope members', () {
    test('a seam envelope carries only frozen members and extensions', () {
      // Arrange.
      final Set<String> allowed = <String>{
        ..._strings(fixture['rfc9457Members']),
        ..._strings(fixture['extensions']),
      };

      // Act.
      final Map<String, Object?> json = portProblem(
        port: PortName.terminal,
        code: PortErrorCode.timeout,
        operation: 'run',
        message: 'Timed out',
        details: <String, Object?>{'executable': 'sleep'},
      ).toJson();

      // Assert.
      expect(json.keys.toSet().difference(allowed), isEmpty);
      expect(allowed, containsAll(<String>['type', 'status', 'recoverable']));
    });

    test('a seam envelope round-trips through the canonical codec', () {
      // Arrange.
      final Problem original = portProblem(
        port: PortName.logging,
        code: PortErrorCode.unavailable,
        operation: 'emit',
        message: 'Sink unavailable',
      );

      // Act.
      final Problem restored = Problem.fromJson(original.toJson());

      // Assert.
      expect(restored, original);
    });

    test(
      'the recoverable extension splits retryable codes from fatal ones',
      () {
        // Arrange & Act.
        final Problem retryable = portProblem(
          port: PortName.metrics,
          code: PortErrorCode.timeout,
          operation: 'flush',
          message: 'Timed out',
        );
        final Problem fatal = portProblem(
          port: PortName.metrics,
          code: PortErrorCode.invalidInput,
          operation: 'emit',
          message: 'Bad sample',
        );

        // Assert.
        expect(retryable.recoverable, isTrue);
        expect(fatal.recoverable, isFalse);
      },
    );
  });

  group('seam contract: failures are values, never exceptions', () {
    test('every fallible seam reports its failure through Result', () async {
      // Arrange.
      final InMemorySystem system = InMemorySystem();
      final InMemoryVfs vfs = InMemoryVfs();
      final InMemoryTerminal terminal = InMemoryTerminal();
      final InMemoryLoggerSink logger = InMemoryLoggerSink()
        ..enqueue(
          portFailure<void>(
            port: PortName.logging,
            code: PortErrorCode.io,
            operation: 'emit',
            message: 'Sink write failed',
          ),
        );
      final InMemoryMetricsCollector metrics = InMemoryMetricsCollector()
        ..enqueue(
          portFailure<void>(
            port: PortName.metrics,
            code: PortErrorCode.io,
            operation: 'emit',
            message: 'Registry write failed',
          ),
        );
      system.enqueueEnvironmentResult(
        portFailure<String?>(
          port: PortName.system,
          code: PortErrorCode.permissionDenied,
          operation: 'environment',
          message: 'Environment unreadable',
        ),
      );

      // Act.
      final Problem systemProblem = expectErr(system.environment('HOME'));
      final Problem vfsProblem = expectErr(await vfs.readText('/missing'));
      final Problem terminalProblem = expectErr(
        await terminal.run(TerminalCommand(executable: 'missing')),
      );
      final Problem logProblem = expectErr(
        logger.emit(
          LogRecord(
            timestamp: DateTime.utc(2026),
            level: LogLevel.warning,
            message: 'warning',
          ),
        ),
      );
      final Problem metricProblem = expectErr(
        metrics.emit(
          MetricRecord(
            timestamp: DateTime.utc(2026),
            name: 'attempts',
            kind: MetricKind.counter,
            value: 1,
          ),
        ),
      );

      // Assert.
      expectPortProblem(
        systemProblem,
        port: PortName.system,
        code: PortErrorCode.permissionDenied,
      );
      expectPortProblem(
        vfsProblem,
        port: PortName.vfs,
        code: PortErrorCode.notFound,
        operation: 'readText',
      );
      expectPortProblem(
        terminalProblem,
        port: PortName.terminal,
        code: PortErrorCode.unexpectedCall,
      );
      expectPortProblem(
        logProblem,
        port: PortName.logging,
        code: PortErrorCode.io,
      );
      expectPortProblem(
        metricProblem,
        port: PortName.metrics,
        code: PortErrorCode.io,
      );
    });

    test('a non-zero child exit stays a captured success', () async {
      // Arrange.
      final InMemoryTerminal terminal = InMemoryTerminal()
        ..enqueue(
          const Ok<TerminalOutput>(
            TerminalOutput(exitCode: 2, stdout: '', stderr: 'usage'),
          ),
        );

      // Act.
      final TerminalOutput output = expectOk(
        await terminal.run(TerminalCommand(executable: 'tool')),
      );

      // Assert.
      expect(output.exitCode, 2);
      expect(output.succeeded, isFalse);
    });
  });
}
