<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AtomiCloud.Diene.Interfaces.UnitTest</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../fixtures/c0/seam-wire-v1.json" Link="fixtures/c0/seam-wire-v1.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AtomiCloud.Diene.Result.TestHelper" />
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Lib/Lib.csproj" />
    <ProjectReference Include="../TestHelper/TestHelper.csproj" />
  </ItemGroup>

</Project>
