// GENERATED by tool/gen_c0_projection.dart from c0-fixtures-r1 — DO NOT EDIT.
library;

/// One immutable prose-source pin carried by the generated C0 projection.
final class C0ConfigSourcePin {
  const C0ConfigSourcePin({
    required this.path,
    required this.sha256,
    this.note,
  });
  final String path;
  final String sha256;
  final String? note;
}

/// Authenticated identity of the neutral C0 release used for this projection.
final class C0ConfigReleaseProvenance {
  const C0ConfigReleaseProvenance({
    required this.releaseId,
    required this.contractVersion,
    required this.releaseDigest,
    required this.c0ProseSource,
    required this.secondarySources,
    required this.formatterPolicyPath,
    required this.formatterPolicySha256,
    required this.prettierExcludedPaths,
  });
  final String releaseId;
  final int contractVersion;
  final String releaseDigest;
  final C0ConfigSourcePin c0ProseSource;
  final List<C0ConfigSourcePin> secondarySources;
  final String formatterPolicyPath;
  final String formatterPolicySha256;
  final List<String> prettierExcludedPaths;
}

/// Generated C0 §3 Config vectors from the neutral release.
final class C0ConfigContract {
  const C0ConfigContract({
    required this.provenance,
    required this.c0Sections,
    required this.layeringAndIndexedList,
    required this.blankIsUnset,
    required this.noJsonNoComma,
    required this.caseInsensitiveKeyMatching,
    required this.finalLayerValidation,
  });
  final C0ConfigReleaseProvenance provenance;
  final List<String> c0Sections;
  final Map<String, Object?> layeringAndIndexedList;
  final Map<String, Object?> blankIsUnset;
  final Map<String, Object?> noJsonNoComma;
  final Map<String, Object?> caseInsensitiveKeyMatching;
  final Map<String, Object?> finalLayerValidation;
}

/// The generated projection of c0-fixtures-r1.
const C0ConfigContract c0ConfigContract = C0ConfigContract(
  provenance: C0ConfigReleaseProvenance(
    releaseId: "c0-fixtures-r1",
    contractVersion: 1,
    releaseDigest:
        "eda331ecba1e899718fa8e8e9b3485d4b746aa66b9c7c1947052ea3e74e2ba45",
    c0ProseSource: C0ConfigSourcePin(
      path: "goals/c0-contracts.md",
      sha256:
          "7dd7a06279f3078a5e195d4103d01ce9fd1b30a7d88178ec37c3e6f0465c7101",
      note:
          "workspace overlay pinned by SHA-256; verbatim excerpts committed under contracts/c0/provenance",
    ),
    secondarySources: <C0ConfigSourcePin>[
      C0ConfigSourcePin(
        path: "goals/lib/dart-family.md",
        sha256:
            "ece72edbb18e2c45f6f16e3a4da2172862f7b044d4218292f90e5219da0b5bd6",
      ),
    ],
    formatterPolicyPath: ".prettierignore",
    formatterPolicySha256:
        "570ca1cd11bb62a56439a92514f10ff3627f864749b4a1f800418aecaca2fa9d",
    prettierExcludedPaths: <String>[
      "/contracts/c0/RELEASE.json",
      "/contracts/c0/cases/config.json",
      "/contracts/c0/cases/problem.json",
      "/contracts/c0/provenance/config-precedence.md",
      "/contracts/c0/provenance/problem-catalog.md",
      "/contracts/c0/provenance/problem-schema.md",
      "/test/fixtures/c0/catalog-entry.json",
      "/test/fixtures/c0/config.json",
      "/test/fixtures/c0/envelope.json",
      "/test/fixtures/c0/type-uri.json",
    ],
  ),
  c0Sections: <String>["§3 Config precedence"],
  layeringAndIndexedList: <String, Object?>{
    "baseYaml": "app:\n  name: base\n  retries: -1\n  tags: [base]\n",
    "defines": <String, Object?>{
      "ACME_APP__NAME": "define",
      "ACME_APP__TAGS__0": "first",
      "ACME_APP__TAGS__1": "second",
    },
    "developmentYaml": "app:\n  name: development\n  tags: [development]\n",
    "expected": <String, Object?>{
      "name": "define",
      "retries": 2,
      "tags": <Object?>["first", "second"],
    },
    "landscapeYaml": "app:\n  name: landscape\n  retries: 2\n",
    "prefix": "ACME_",
  },
  blankIsUnset: <String, Object?>{
    "baseYaml": "app:\n  name: base\n  retries: 1\n  tags: [base]\n",
    "defines": <String, Object?>{"ACME_APP__NAME": "", "ACME_APP__TAGS__0": ""},
    "expected": <String, Object?>{
      "name": "base",
      "retries": 1,
      "tags": <Object?>["base"],
    },
    "prefix": "ACME_",
  },
  noJsonNoComma: <String, Object?>{
    "rejected": <Object?>[
      <String, Object?>{
        "baseYaml": "app:\n  name: service\n  retries: 1\n  tags: []\n",
        "defines": <String, Object?>{
          "ACME_APP__TAGS": "[\"first\",\"second\"]",
        },
        "name": "JSON",
        "prefix": "ACME_",
      },
      <String, Object?>{
        "baseYaml": "app:\n  name: service\n  retries: 1\n  tags: []\n",
        "defines": <String, Object?>{"ACME_APP__TAGS": "first,second"},
        "name": "comma-separated",
        "prefix": "ACME_",
      },
    ],
  },
  caseInsensitiveKeyMatching: <String, Object?>{
    "baseYaml": "app-settings:\n  displayName: base\n",
    "prefix": "ACME_",
    "variants": <Object?>[
      <String, Object?>{
        "defineKey": "ACME_APP_SETTINGS__DISPLAY_NAME",
        "expectedValue": "snake",
      },
      <String, Object?>{
        "defineKey": "acme_app-settings__display-name",
        "expectedValue": "kebab",
      },
      <String, Object?>{
        "defineKey": "AcMe_AppSettings__DisplayName",
        "expectedValue": "pascal",
      },
    ],
  },
  finalLayerValidation: <String, Object?>{
    "invalid": <String, Object?>{
      "baseYaml": "app:\n  name: service\n  retries: -1\n  tags: []\n",
      "defines": <String, Object?>{},
      "prefix": "ACME_",
    },
  },
);
