$schema: ./schema.json
app:
  landscape: raichu
branding:
  appName: Diene Mobile
  iconAsset: assets/brand/icon-raichu.png
theme:
  primary: '#0F766E'
  secondary: '#EA580C'
auth:
  endpoint: https://auth.platform.raichu.example
  resource: https://api.platform.raichu.example
  redirectUri: cloud.atomi.raichu.platform.service.app://callback
api:
  baseUrl: https://api.platform.raichu.example
