# ### go-base-chart
# #### source: go-base
apiVersion: v2
name: fleet-operator
description: Manager chart for the AtomiCloud fleet operator (CRDs, RBAC, deployment, observability)
type: application
version: 0.1.0
appVersion: '0.1.0'
