#!/usr/bin/env bash
set -euo pipefail

mode="${1:-}"
profile="${2:-}"

[ -z "${mode}" ] && echo "❌ coverage mode not set" >&2 && exit 1
[ -z "${profile}" ] && echo "❌ coverage profile not set" >&2 && exit 1
[ ! -s "${profile}" ] && echo "❌ coverage profile '${profile}' is empty" >&2 && exit 1

marker="$(yq -r ".tiers.${mode}.pathMarker" .config/go-base.coverage.yaml)"
threshold="$(yq -r ".tiers.${mode}.threshold" .config/go-base.coverage.yaml)"
scope="$(sed 's|^/||; s|/$||' <<<"${marker}")"
[ ! -d "${scope}" ] && echo "❌ ${mode} coverage scope '${marker}' is not a directory in this repository" >&2 && exit 1

paths="$(awk 'NR > 1 {sub(/:[0-9].*/, "", $1); print $1}' "${profile}" | sort -u)"
[ -z "${paths}" ] && echo "❌ coverage profile '${profile}' has no source files" >&2 && exit 1
escaped="$(awk -v marker="${marker}" 'index($0, marker) == 0 {print; exit}' <<<"${paths}")"
[ -n "${escaped}" ] && echo "❌ ${mode} coverage escaped its '${marker}' scope" >&2 && exit 1

# Derive the expected surface from the tree, minus what the Go tool and the lint exclusions already ignore, because a source the profile never measured escapes both the scope check and the percentage.
expected="$(find "${scope}" -type f -name '*.go' -not -name '*_test.go' -not -path '*/vendor/*' -not -path '*/testdata/*' -print0 | sort -z | xargs -0 -r gawk -v IGNORECASE=1 'FNR == 1 && !/code generated|autogenerated|do not edit/ {print FILENAME} FNR == 1 {nextfile}')"
[ -z "${expected}" ] && echo "❌ ${mode} coverage scope '${scope}/' holds no measurable Go source" >&2 && exit 1
covered="$(awk -v marker="${marker}" '{print substr($0, index($0, marker) + 1)}' <<<"${paths}" | sort -u)"
missing="$(gawk -v covered="${covered}" 'BEGIN {split(covered, rows, "\n"); for (row in rows) seen[rows[row]] = 1} !($0 in seen) {print; exit}' <<<"${expected}")"
[ -n "${missing}" ] && echo "❌ ${mode} coverage is missing '${missing}': every Go source beneath '${scope}/' must be measured" >&2 && exit 1

total="$(go tool cover -func="${profile}" | awk '/^total:/ {gsub(/%/, "", $3); print $3}')"
below="$(awk -v total="${total}" -v threshold="${threshold}" 'BEGIN {print (total + 0 < threshold + 0) ? "true" : "false"}')"
[ "${below}" = "true" ] && echo "❌ ${mode} coverage ${total}% is below ${threshold}%" >&2 && exit 1

echo "✅ ${mode} coverage is complete, scoped, and ${total}%"
