#!/usr/bin/env bash
set -euo pipefail

# Asserts ONE property against flake.nix: every nixpkgs input is pinned to an
# exact commit, and nothing floats on a channel branch or a tag.
#
# A channel ref like `nixos-unstable` or `nixos-26.05` moves under us, which means
# the same tree builds differently on two different days. Moving a pin must be a
# deliberate human-cadence action, so this gate refuses any ref that is not a
# 40-character commit SHA.
#
# flake.nix, not flake.lock, is the authority the gate reads. A lock can be
# regenerated by anyone at any time and a floating URL simply relocks to whatever
# is upstream that day, so a lock alone never proves the pin was intended. The
# root layer of this repository has no lock at all, which makes the URL its only
# pin. Where a lock IS committed - as it is here - it is checked as a second copy
# that must agree with the URL, never as a substitute for it.
#
# This replaces the older gate, which reconciled flake.nix against a second
# hand-maintained record in nix/snapshots/nixpkgs.json. That file is gone: two
# records of one fact can disagree, and the gate spent its assertions on the
# disagreement rather than on the property that matters.

fail() {
  echo "❌ $1" >&2
  exit 1
}

[ -f flake.nix ] || fail "flake.nix is missing - run this from the repository root"

# The snapshot file is deliberately deleted. If it comes back, two records of the
# pin exist again and this gate is no longer reading the only authority.
[ -e nix/snapshots/nixpkgs.json ] &&
  fail "nix/snapshots/nixpkgs.json is back - flake.nix is the single authority for the pin"

# Strip full-line comments before parsing so a commented-out example input can
# neither satisfy nor trip the gate.
inputs="$(rg -N -v '^\s*#' flake.nix | rg -No '^\s*([A-Za-z0-9_-]+)\.url\s*=\s*"([^"]+)"' -r '$1 $2' || true)"

[ -z "${inputs}" ] && fail "no '<name>.url = \"...\";' inputs found in flake.nix - the parser matched nothing, so a green here would prove nothing"

pinned=0
floating=0
declare -A scoped=()

while read -r name url; do
  [ -z "${name}" ] && continue

  # An input is in scope if its NAME says nixpkgs or its URL points at the
  # nixpkgs repository. Either alone is enough: a future `nixpkgs-2505` is caught
  # by the name even if someone rewrites the URL form, and an input named
  # something else that still pulls nixpkgs is caught by the URL.
  case "${name}:${url}" in
  nixpkgs*:* | *:*NixOS/nixpkgs*) ;;
  *) continue ;;
  esac

  # Only the github:NixOS/nixpkgs/<ref> form is understood. Anything else - a
  # tarball URL, a flake registry alias, a path - is refused rather than guessed
  # at, because this gate must never pass an input it cannot actually read.
  ref="${url#github:NixOS/nixpkgs/}"
  if [ "${ref}" = "${url}" ]; then
    echo "  ✗ ${name} = ${url}" >&2
    echo "    not a github:NixOS/nixpkgs/<rev> URL - this gate cannot prove it is pinned" >&2
    floating=$((floating + 1))
    continue
  fi

  # `?ref=`, `?rev=` and `/branch` all land here as a non-SHA and are refused.
  if [[ ${ref} =~ ^[0-9a-f]{40}$ ]]; then
    echo "  ✓ ${name} = ${ref}"
    scoped["${name}"]="${ref}"
    pinned=$((pinned + 1))
  else
    echo "  ✗ ${name} = ${ref}" >&2
    echo "    floating: a channel branch, tag or ref moves upstream and changes the build" >&2
    floating=$((floating + 1))
  fi
done <<<"${inputs}"

# A repository with zero nixpkgs inputs is not a passing repository, it is a
# repository this gate failed to read. Absence gets its own exit code so it can
# never be mistaken for a clean run.
[ "${pinned}" -eq 0 ] && [ "${floating}" -eq 0 ] &&
  fail "no nixpkgs input found in flake.nix - either the flake is broken or this gate's parser is"

[ "${floating}" -gt 0 ] &&
  fail "${floating} nixpkgs input(s) are not commit-pinned"

# If a lock is committed, it is a second copy of the pin and must agree with it.
#
# Only the ROOT's own direct inputs are checked. flake.lock also carries a
# nixpkgs for every dependency that pulls one - flake-utils, treefmt-nix,
# pre-commit-hooks, the atomi registry - and those revisions belong to those
# flakes. This repository cannot pin them without overriding upstream, which is a
# different decision from the one this gate enforces, so asserting on them would
# only produce a red nobody here can fix.
if [ -f flake.lock ]; then
  for name in "${!scoped[@]}"; do
    node="$(jq -r --arg n "${name}" '.nodes.root.inputs[$n] // ""' flake.lock)"
    [ -z "${node}" ] &&
      fail "flake.nix declares input '${name}' but flake.lock has no root entry for it - the lock is stale, run 'nix flake lock'"
    locked="$(jq -r --arg n "${node}" '.nodes[$n].locked.rev // ""' flake.lock)"
    [ "${locked}" != "${scoped[${name}]}" ] &&
      fail "flake.lock has '${name}' at '${locked:-nothing}' but flake.nix pins '${scoped[${name}]}' - the lock is stale, run 'nix flake lock'"
  done
fi

# Kept from the previous gate: these are separate facts about the registry and
# the package set, not restatements of the pin.
#
# The registry is held to the SAME rule as nixpkgs above, for the same reason.
# `v3` and `v3.12` are MOVING tags - the registry retargets them at every v3.x
# release - so pinning to either reproduces the exact fault this gate exists to
# stop, merely spelled as a tag instead of a branch.
#
# That is measured, not hypothetical. This repository shipped
# `nix-registry/v3` in flake.nix while flake.lock sat at v3.7.0, and the moving
# tag had advanced five minor versions to v3.12.0 underneath it. Nothing went
# red, because the previous form of this check string-matched the alias `v3`
# and never looked at which version it resolved to.
#
# Only a three-part v3.<minor>.<patch> is accepted: `v3` and `v3.12` are refused
# as moving, and a v4 series is refused as a major this tree has not adopted.
rg -q 'atomipkgs\.url = "github:AtomiCloud/nix-registry/v3\.[0-9]+\.[0-9]+";' flake.nix ||
  fail "atomipkgs must be pinned to an exact v3 series version (v3.<minor>.<patch>), not the moving 'v3' or 'v3.<minor>' alias"
rg -q 'nix-2605' nix/packages.nix ||
  fail "nix/packages.nix is missing nix-2605"
rg -q 'pkgs-2605' flake.nix ||
  fail "flake.nix is missing pkgs-2605"
if rg -q 'nix-2511|pkgs-2511' flake.nix nix/*.nix; then
  fail "stale 25.11 channel names remain"
fi

echo "✅ all ${pinned} nixpkgs input(s) are commit-pinned"
