#!/usr/bin/env bash
set -euo pipefail

# Captured-env pilot (E4). Captures each development shell once with
# `nix print-dev-env` so probe commands can source the capture instead of paying a
# fresh `nix develop` evaluation per execution. Consumed by probes/lib/helpers.ts
# through PROBE_CAPTURED_ENV; with that variable unset nothing here is used.
#
# Usage:
#   scripts/probe-env-capture.sh <out-dir> [flake-dir]
#   scripts/probe-env-capture.sh --verify <out-dir> [flake-dir]
#
# The capture is only valid for the flake.lock it was taken from, so the lock's
# hash is recorded next to it and --verify refuses a stale directory. Every file is
# written to a temporary name in the same directory and renamed into place, so a
# reader either sees the previous capture or the new one and never a partial one.

shells="${PROBE_ENV_CAPTURE_SHELLS:-default ci cd releaser}"

# `nix develop -c` evaluates the shell hook after loading the environment;
# `nix print-dev-env` only defines it. Appending the eval keeps the captured
# environment equivalent to a real shell entry. Set to 0 to capture without it.
run_shell_hook="${PROBE_ENV_CAPTURE_SHELL_HOOK:-1}"

die() {
  echo "❌ $*" >&2
  exit 1
}

hash_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${file}" | cut -d' ' -f1
  else
    die "no sha256sum or shasum available to hash ${file}"
  fi
}

verify=0
if [ "${1:-}" = "--verify" ]; then
  verify=1
  shift
fi

out_dir="${1:-${PROBE_CAPTURED_ENV:-}}"
flake_dir="${2:-${PWD}}"

[ -n "${out_dir}" ] || die "usage: $0 [--verify] <out-dir> [flake-dir]"
[ -f "${flake_dir}/flake.lock" ] || die "'${flake_dir}/flake.lock' is missing"

lock_hash="$(hash_file "${flake_dir}/flake.lock")"

if [ "${verify}" = "1" ]; then
  [ -f "${out_dir}/CAPTURE.env" ] || die "'${out_dir}/CAPTURE.env' is missing — nothing was captured here"
  recorded="$(sed -n 's/^FLAKE_LOCK_SHA256=//p' "${out_dir}/CAPTURE.env")"
  [ "${recorded}" = "${lock_hash}" ] || die "captured env is stale: flake.lock is ${lock_hash}, capture is ${recorded}"
  for shell in ${shells}; do
    [ -s "${out_dir}/${shell}.sh" ] || die "captured env is incomplete: '${out_dir}/${shell}.sh' is missing or empty"
  done
  echo "✅ captured env in '${out_dir}' matches flake.lock ${lock_hash}"
  exit 0
fi

mkdir -p "${out_dir}"
out_dir="$(cd "${out_dir}" && pwd)"

for shell in ${shells}; do
  target="${out_dir}/${shell}.sh"
  staging="${out_dir}/.${shell}.$$.sh"
  echo "→ capturing .#${shell}"
  {
    printf '# generated by scripts/probe-env-capture.sh — do not edit\n'
    printf '# flake=%s shell=%s flake.lock=%s\n' "${flake_dir}" "${shell}" "${lock_hash}"
    (cd "${flake_dir}" && nix print-dev-env --no-write-lock-file ".#${shell}")
    if [ "${run_shell_hook}" = "1" ]; then
      cat <<'HOOK'

# `nix develop -c` runs the shell hook after loading the environment; print-dev-env
# only defines it, so the capture runs it here to stay equivalent to a real entry.
eval "${shellHook-}"
HOOK
    fi
  } >"${staging}"
  [ -s "${staging}" ] || {
    rm -f "${staging}"
    die "nix print-dev-env produced nothing for .#${shell}"
  }
  mv -f "${staging}" "${target}"
done

manifest_staging="${out_dir}/.CAPTURE.$$.env"
{
  printf 'FLAKE_DIR=%s\n' "${flake_dir}"
  printf 'FLAKE_LOCK_SHA256=%s\n' "${lock_hash}"
  printf 'SHELLS=%s\n' "${shells}"
  printf 'SHELL_HOOK=%s\n' "${run_shell_hook}"
  printf 'CAPTURED_AT_EPOCH=%s\n' "$(date -u +%s)"
  printf 'NIX_VERSION=%s\n' "$(nix --version | head -n 1)"
} >"${manifest_staging}"
mv -f "${manifest_staging}" "${out_dir}/CAPTURE.env"

echo "✅ captured ${shells} into '${out_dir}' for flake.lock ${lock_hash}"
