events {}
http {
  access_log /dev/stdout;
  error_log /dev/stderr notice;
  upstream mercury_lapras {
    server mercury-lapras:8080;
  }
  upstream mercury_farfetch {
    server mercury-farfetch:8080;
  }
  upstream sink_coordinate {
    server sink-coordinate:8080;
  }
  server {
    listen 443 ssl;
    server_name mercury.test localhost;
    ssl_certificate /run/sit/ca/tls.pem;
    ssl_certificate_key /run/sit/ca/tls-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    location /__public-sink/ {
      proxy_pass http://sink_coordinate/;
    }
    location /__farfetch-landscape/ {
      proxy_pass http://mercury_farfetch/internal/landscape/v1/;
    }
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_pass http://mercury_lapras;
    }
  }
}
