# ### workspace-ci
# #### source: workspace
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  precommit:
    name: Pre-Commit
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit

  helm:
    name: Helm Chart
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      chart_path: ./infra/root_chart

  helm-wrapper:
    name: Helm Wrapper
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-helm-wrapper.yaml
    secrets: inherit

  garden-parity:
    name: Garden Parity
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-garden-parity.yaml
    secrets: inherit
