# ### dart-lib-reusable-gates
# #### source: lib/dart/problems
name: ⚡ Reusable Dart Gates

on:
  workflow_call:

jobs:
  gates:
    name: Dart Coverage, Meta, Deadcode, Publish Dry-Run
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - name: Gate suite
        run: nix develop .#ci -c ./scripts/ci/gates.sh
