# ### dart-result-reusable-publish
# #### source: lib/dart/result
name: ⚡ Reusable Dart Publish

on:
  workflow_call:
    secrets:
      PUB_CREDENTIALS_JSON:
        required: true

jobs:
  publish:
    name: Publish to pub.dev
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - name: Publish library
        env:
          PUB_CREDENTIALS_JSON: ${{ secrets.PUB_CREDENTIALS_JSON }}
        run: nix develop .#cd -c ./scripts/ci/publish.sh
