name: ⚡ Reusable Go Typecheck

on:
  workflow_call:

jobs:
  typecheck:
    name: Go Typecheck
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-go@v2
      - name: Run Go typecheck
        run: nix develop .#ci -c ./scripts/ci/typecheck.sh
