# ### flutter-base-reusable-test
# #### source: flutter-base
name: ⚡ Reusable Flutter Test

on:
  workflow_call:

jobs:
  test:
    name: Flutter Analyze and Test
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - name: Analyze and test
        run: nix develop .#ci -c ./scripts/ci/test.sh
